
project_id = "ygvocurodighahfjyjnw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.menu-suggestions]
verify_jwt = false
